// <auto-generated />
namespace MVC_ViewModel_ModalWindow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClassAddedForMasterDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassAddedForMasterDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202403310508548_ClassAddedForMasterDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
